using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Health_Station.Models
{
    public enum ActivityType : ulong
    {
        AmericanFootball = 1,
        Archery = 2,
        AustralianFootball = 3,
        Badminton = 4,
        Baseball = 5,
        Basketball = 6,
        Bowling = 7,
        Boxing = 8,
        Climbing = 9,
        Cricket = 10,
        CrossTraining = 11,
        Curling = 12,
        Cycling = 13,
        Dance = 14,
        DanceInspiredTraining = 15,
        Elliptical = 16,
        EquestrianSports = 17,
        Fencing = 18,
        Fishing = 19,
        FunctionalStrengthTraining = 20,
        Golf = 21,
        Gymnastics = 22,
        Handball = 23,
        Hiking = 24,
        Hockey = 25,
        Hunting = 26,
        Lacrosse = 27,
        MartialArts = 28,
        MindAndBody = 29,
        MixedMetabolicCardioTraining = 30,
        PaddleSports = 31,
        Play = 32,
        PreparationAndRecovery = 33,
        Racquetball = 34,
        Rowing = 35,
        Rugby = 36,
        Running = 37,
        Sailing = 38,
        SkatingSports = 39,
        SnowSports = 40,
        Soccer = 41,
        Softball = 42,
        Squash = 43,
        StairClimbing = 44,
        SurfingSports = 45,
        Swimming = 46,
        TableTennis = 47,
        Tennis = 48,
        TrackAndField = 49,
        TraditionalStrengthTraining = 50,
        Volleyball = 51,
        Walking = 52,
        WaterFitness = 53,
        WaterPolo = 54,
        WaterSports = 55,
        Wrestling = 56,
        Yoga = 57,
        Barre = 58,
        CoreTraining = 59,
        CrossCountrySkiing = 60,
        DownhillSkiing = 61,
        Flexibility = 62,
        HighIntensityIntervalTraining = 63,
        JumpRope = 64,
        Kickboxing = 65,
        Pilates = 66,
        Snowboarding = 67,
        Stairs = 68,
        StepTraining = 69,
        WheelchairWalkPace = 70,
        WheelchairRunPace = 71,
        Other = 3000
    }
}
